# Exported from Render on 2024-09-15T12:41:06Z
services:
- type: web
  name: cpms-app
  runtime: static
  repo: https://github.com/MoinMN/cpms
  buildCommand: npm run build
  staticPublishPath: dist
  routes:
  - type: rewrite
    source: /*
    destination: /
  rootDir: frontend
version: "1"
